import { Hero, Navbar } from "@/components";
import { Experience } from "@/components/experience";
import { Projects } from "@/components/projects";
import { Skills } from "@/components/skills";
import Head from "next/head";
import { Fragment } from "react";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Shubham Patrick | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Experience />
        <Skills />
        <Projects />
      </main>
    </Fragment>
  );
}
